name: Testing failing steps
on: workflow_dispatch
jobs:
  test-failing-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: |
          echo "This is Step 1"
          invalidcommand # This will cause an error because "invalidcommand" does not exist
        # Annotation for Step 1
        id: step1

      - name: Step 2
        continue-on-error: true
        run: |
          echo "This is Step 2"
          exit 1
        # Annotation for Step 2
        id: step2

      - name: Step 3
        continue-on-error: true
        run: |
          echo "This is Step 3"
          exit 1
        # Annotation for Step 3
        id: step3
