name: Testing failing steps
on: workflow_dispatch
jobs:
  test-failing-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: exit 1
        continue-on-error: true
        # Annotation for Step 1
        id: step1
        shell: bash
        run: |
          echo "This is Step 1"
          exit 1

      - name: Step 2
        run: exit 1
        continue-on-error: true
        # Annotation for Step 2
        id: step2
        shell: bash
        run: |
          echo "This is Step 2"
          exit 1

      - name: Step 3
        run: exit 1
        continue-on-error: true
        # Annotation for Step 3
        id: step3
        shell: bash
        run: |
          echo "This is Step 3"
          exit 1
